<template>
  <div id="wrapper">
    <top-nav></top-nav>
    <main>
      <section class="app-description">
        <el-collapse v-model="activeAccordion" accordion @change="handleAccordionChange">
          <el-collapse-item title="About" name="#about">
            <p><strong><a href="/weaving">Weaving Music</a></strong> is an exploration of the materiality of sound through the metaphor of weaving, with the weaving loom re-imagined as a music sequencer. The seeds of this project were formed when first encountering grid notation for weaving patterns in Anni Albers' <em>On Weaving</em>, which gave the immediate impression of rhythmic music notation.</p>
            <figure>
              <img src="https://reubenson-portfolio.s3.us-east-1.amazonaws.com/assets/on-weaving.jpeg" alt="weaving notation from Anni Albers" class="">
              <figcaption>Image from Anni Albers' <em>On Weaving</em> (1965, Wesleyan University Press)</figcaption>
            </figure>
            <p>In the summer of 2019, I began developing this project during a <a href="https://elektronmusikstudion.se/composers/2019/1013-reuben-son-ems-10-19-june-2019">residency at EMS</a> in Stockholm, where I used MIDI signals generated by this app to control voicings produced on their Buchla and Serge synthesizer systems.</p>
            <figure>
              <img src="https://reubenson-portfolio.s3.us-east-1.amazonaws.com/assets/buchla.jpg" alt="buchla modular synthesizer" class="flex-half">
              <img src="https://reubenson-portfolio.s3.us-east-1.amazonaws.com/assets/serge.jpg" alt="serge modular synthesizer" class="flex-half">
            <figcaption>Buchla and Serge synthesizers at EMS (photos by the artist)</figcaption>
            </figure>
            <p>In the end, this project attempts a fairly straightforward translation of weaving notation to music notation, in that patterns are read from left to right as columns along the warp (vertical threads hung on a a weaving loom). In the current version, there are two ways of interpreting how a column should be handled: as octaves (in octave mode) or as a canon (in canon mode). These different mode offer different expressions of the underlying harmonic structure, which this app leaves intentionally simplified (as a selection from a variety of chords), such that the resulting music is an expression of an underlying harmonic structure.</p>
            <p>In sharing this software, my hope is that you too may find it useful for harmonic and rhythmic research and discovery, sharing some similarity in intent to the historical <a href="https://till.com/articles/muse/">Triadex Muse</a>.</p>
          </el-collapse-item>
          <el-collapse-item title="Getting Started" class="presets" name="#presets">
            <p>The following presets may be helpful for you to become familar with the inner workings of this app.</p>
            <header>Preset #1</header>
            <p>
              This preset has the feelings of passing clouds, like a slower movement from one of Keith Fullerton Whitman's <a href="https://keithfullertonwhitman.com/generators"><i>Generators</i></a> or his <i>Playthroughs</i> album. The slow BPM and usage of <i>canon</i> Stack Type allows for a gentle cycling across the <i>maj7</i> chord, arranged here over a two-octave register.
            </p>
            <div class="spotify-embed">
              <iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/0jV5pkyZByn7pV12Rzbtuu?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
            </div>
            <p>    
              To explore this preset further, try clicking <strong>Randomize note sequence</strong> to obtain a new random pattern for the given chord, and play with the <strong>Weave X</strong> and <strong>Weave Y</strong> parameters to change the sparseness of the voicings.
            </p>
            <el-button
              class="border"
              @click="store.applyPreset(1)"
              >Apply Preset #1</el-button>
            <header>Preset #2</header>
            <p>
              This preset is at the other of the spectrum, a frenetic arpeggiation of varying pipe organ tonalities, reminiscent of a section from Peter Hamel or Phillip Glass. The organ sonority comes from the use of <em>octave</em> <strong>Stack Type</strong>, which means that a column of notes is played as octaves.
            </p>
            <div class="spotify-embed">
              <iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/4zsXWPvdt7GMoWGnxTfeKP?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
            </div>
            <p>
              To explore this preset further, try raising up the <strong>Euclidean Density</strong> setting to fill in the octave harmonic spectrum, or bring it down to 1 to hear each the notes playing in isolation across the octave registers. You may also play with the <strong>Sine Waveform</strong> to change the melody derived. Simpler waveforms closer to the middle range will allow you to easily hear how the pitch of the notes follows the contours of the waveform. This will also register visibly if you include the <strong>Euclidean Density</strong> to its maximum setting.
            </p>
            <el-button
              class="border"
              @click="store.applyPreset(2)"
              >Apply Preset #2</el-button>
              <header>Preset #3</header>
            <p>
              This preset takes on the more extreme high register, playing a cluster of notes that are close enough in frequency to produce audible difference tones, in the manner of <a href="https://caesuramag.org/posts/bret-schneider-groundwork-for-a-study-of-maryanne-amacher">Maryanne Amacher's explorations of Marvin Minksy's Triadex Muse</a>.
            </p>
            <p>
              To bring this back into more traditionally musical territory, simply move the <strong>Lower Register</strong> value back down.
            </p>
            <el-button
              class="border"
              @click="store.applyPreset(3)"
              >Apply Preset #3</el-button>
          </el-collapse-item>
        </el-collapse>
      </section>
      <settings-pane :title="'MIDI Settings'" v-if="!useWebAudio">
        <p class="setting-description">Select Output Port</p>
          <client-only>
            <el-select v-model="midiOutputPort">
              <el-option
                v-for="item in outputPorts"
              />
            </el-select>
        </client-only>
      </settings-pane>
      <settings-pane :title="'Time Settings'">
        <p class="settings-description">Change the BPM (beats per minute) to modify how fast we advance through the sequence controlled in <em>Music Settings</em></p>
        <el-input v-model="bpm" placeholder="BPM">
          <template #prepend>BPM</template>
        </el-input>
        <el-slider
          label="clock"
          :min="50"
          :max="1000"
          :step="10"
          v-model="bpm"
          ></el-slider>
        <p class="setting-title">Note Duration</p>
        <el-input-number 
          v-model="noteHoldCount"
          :step="1"
          :min="0"
          :max="8"/>
      </settings-pane>
      <settings-pane :title="'Music Settings'">
        <p class="settings-description">These settings modify the underlying sequence of notes played as we advance from left to right in the <em>Weaving Swatch</em> below.</p>
        <div>
          <p class="setting-title">Sequence Type</p>
          <client-only>
            <el-popover
              class="settings-info"
              placement="top-start"
              title="Sequence Type"
              :width="200"
              trigger="click"
              content="select the type of music sequence: random is random, and 'sine' provides a waveform that produces a set of notes."
            >
              <template #reference>
                <el-button class="m-2">&#9432;</el-button>
              </template>
            </el-popover>
          </client-only>
          <!-- <p class="setting-description" v-if="waveformType === 'random'">The sequence of notes is randomly picked from the chord specified below</p>
          <p class="setting-description" v-if="waveformType === 'sine'">The sequence of notes is picked based on the shape of this waveform</p> -->
          <client-only>
            <el-select
              v-model="sequenceType"
            >
              <el-option
                v-for="item in sequenceTypeOptions"
                :key="item"
                :label="item"
                :value="item"
              />
            </el-select>
          </client-only>
        </div>
        <div>
          <p class="setting-title">Root Note</p>
          <client-only>
            <el-popover
              class="settings-info"
              placement="top-start"
              title="Root Note"
              :width="200"
              trigger="click"
              content="Root note (tonic) of the selected chord"
            >
              <template #reference>
                <el-button class="m-2">&#9432;</el-button>
              </template>
            </el-popover>
          </client-only>
          <client-only>
            <el-select
              v-model="rootNote"
            >
              <el-option
                v-for="item in tonicOptions"
                :key="item"
                :label="item"
                :value="item"
              />
            </el-select>
          </client-only>
          <p class="setting-title">Chord Name</p>
          <client-only>
            <el-popover
              class="settings-info"
              placement="top-start"
              title="Chord Name"
              :width="200"
              trigger="click"
              content="The notes in the selected chord will be used to populate the note sequence"
            >
              <template #reference>
                <el-button class="m-2">&#9432;</el-button>
              </template>
            </el-popover>
          </client-only>
          <client-only>
            <el-select
              v-model="noteScale"
            >
              <el-option
                v-for="item in chordOptions"
                :key="item"
                :label="item"
                :value="item"
              />
            </el-select>
          </client-only>
          <notation />
        </div>
        <div>
          <p class="setting-title">Filter chord by number of notes</p>
          <client-only>
            <el-popover
              class="settings-info"
              placement="top-start"
              title="Chord Name"
              :width="200"
              trigger="click"
              content="Select lower values to filter the chord options with fewer notes"
            >
              <template #reference>
                <el-button class="m-2">&#9432;</el-button>
              </template>
            </el-popover>
          </client-only>
          <client-only>
            <el-select
              label="Filter chord selector by number of notes"
              v-model="chordSizeFilter"
            >
              <el-option
                v-for="item in [3, 4, 5, 6, 7]"
                :key="item"
                :label="item"
                :value="item"
              />
            </el-select>
          </client-only>
        </div>
        <div>
          <p class="setting-title">Lower Register</p>
          <client-only>
            <el-popover
              class="settings-info"
              placement="top-start"
              title="Lower Register"
              :width="200"
              trigger="click"
              content="Select lower values to filter the chord options with fewer notes"
            >
              <template #reference>
                <el-button class="m-2">&#9432;</el-button>
              </template>
            </el-popover>
          </client-only>
          <el-slider
            :min="0"
            :max="upperRegisterMax"
            :step="1"
            show-stops
            v-model="rangeMin"
          ></el-slider>
        </div>
        <div>
          <p class="setting-title">Upper Register</p>
          <client-only>
            <el-popover
              class="settings-info"
              placement="top-start"
              title="Upper Register"
              :width="200"
              trigger="click"
              content="Select the upper register for the note sequence"
            >
              <template #reference>
                <el-button class="m-2">&#9432;</el-button>
              </template>
            </el-popover>
          </client-only>
          <el-slider
            :min="0"
            :max="upperRegisterMax"
            :step="1"
            show-stops
            v-model="rangeMax"
          ></el-slider>
        </div>
        <client-only>
          <p class="setting-title">Stack Type</p>
          <el-popover
              class="settings-info"
              placement="top-start"
              title="Stack Type"
              :width="200"
              trigger="click"
              content="Stack refers to a vertical column of notes, which are played as the sequencer moves from left to right. In 'octave' mode, each subsequent row plays the same note as the row above it, except an octave higher. In 'canon' mode, each row plays the same note as the column before, creating a repeating behavior"
            >
              <template #reference>
                <el-button class="m-2">&#9432;</el-button>
              </template>
            </el-popover>
          <el-select
              label="Stack Type"
              v-model="stackType"
            >
              <el-option
                v-for="item in stackTypeOptions"
                :key="item"
                :label="item"
                :value="item"
              />
            </el-select>
        </client-only>
        <div />
        <el-button
          class="border"
          v-if="musicStore.sequenceType === 'random'"
            @click="musicStore.handleRandomize"
          >Randomize note sequence</el-button>
        <div v-if="musicStore.sequenceType === 'sine'">
          <p class="setting-title">Sine Waveform</p>
          <p class="setting-description">This waveform is used to generate the note sequence. By adding negative or positive harmonics to a sine wave, this waveform can be transformed from a saw wave to a sine wave.</p>
          <el-slider
            :min="-8"
            :max="8"
            :step="0.1"
            v-model="sineHarmonics"
            ></el-slider>
          <client-only>
            <waveform></waveform>
          </client-only>
        </div>
      </settings-pane>
      <settings-pane :title="'Weave Settings'">
        <p class="settings-description">
          In weaving, <em>warp</em> refers to the vertical lines and <em>warp</em> refers to the horizontal lines, which are woven between the  weft. In the swatch below, the warp (vertical) lines represent notes in the note sequence generated by the <em>Music Settings</em>, and the weft (horizontal) lines represent individual voices that play the notes defined by the warp. To simplify the resulting tonality, the weft lines are handles as octaves, such that when more than one is played simultaneously, they alter the timbre of the voicing rather simply, as stacked octaves. This results in a translation of the weaving pattern that would be rather familiar to anyone who has previously used an MPC sequencer.
        </p>
        <div>
          <p class="setting-title">Warp Count</p>
          <client-only>
            <el-popover
              class="settings-info"
              placement="top-start"
              title="Warp Count"
              :width="200"
              trigger="click"
              content="In weaving, a warp is thread hung vertically. In our sequencer, a warp represents a note in the note sequence"
            >
              <template #reference>
                <el-button class="m-2">&#9432;</el-button>
              </template>
            </el-popover>
          </client-only>
          <el-input-number 
            v-model="swatchWidth"
            :step="1"
            :min="2"/>
        </div>
        <div>
          <p class="setting-title">Weft Count</p>
          <client-only>
            <el-popover
              class="settings-info"
              placement="top-start"
              title="Weft Count"
              :width="200"
              trigger="click"
              content="In weaving, a warp is thread hung vertically. In our sequencer, a warp represents a note in the note sequence"
            >
              <template #reference>
                <el-button class="m-2">&#9432;</el-button>
              </template>
            </el-popover>
          </client-only>
          <el-input-number 
            v-model="swatchDepth"
            :step="1"
            :min="2"/>
        </div>
        <div>
          <p class="setting-title">Pattern Type</p>
          <client-only>
            <el-popover
              class="settings-info"
              placement="top-start"
              title="Pattern Type"
              :width="200"
              trigger="click"
              content="Weave: apply traditional weaving patterns. Euclidean: apply a 'euclidean' algorithm, which will construct a pattern in which notes are evenly spaced across the sequence"
            >
              <template #reference>
                <el-button class="m-2">&#9432;</el-button>
              </template>
            </el-popover>
          </client-only>
          <client-only>
            <el-select
              v-model="patternType"
            >
              <el-option
                v-for="item in patternOptions"
                :key="item"
                :label="item"
                :value="item"
              />
            </el-select>
          </client-only>
        </div>
        <div v-if="patternType === 'weave'">
          <p>Weave X</p>
          <el-slider
          v-model="weaveX"
          :min="1"
          :max="8"
          :step="1"
        ></el-slider>
        <p>Weave Y</p>
        <el-slider
          v-if="patternType === 'weave'"
          v-model="weaveY"
          :min="1"
          :max="8"
          :step="1"
        ></el-slider>
        </div>
        <div v-if="patternType === 'euclidean'">
          <p>Euclidean Density</p>
          <el-slider
            v-model="euclideanCount"
            :min="1"
            :max="swatchWidth"
            :step="1"
          ></el-slider>
        </div>
      </settings-pane>
      <swatch></swatch>
    </main>
  </div>
</template>

<script setup>
  import TopNav from './TopNav';
  import Swatch from './Swatch';
  import SettingsPane from './_SettingsPane';
  import Waveform from './Waveform';
  import Notation from './Notation';
  import { useStore } from '@/store/main';
  import { useMusicStore } from '@/store/music-settings';
  import { useWeaveStore } from '@/store/weave-settings';
  import { storeToRefs } from 'pinia';
  import midi from '~/lib/midi';
  import hotkeys from 'hotkeys-js';
  import _ from 'lodash';
  const { $event } = useNuxtApp();

  const store = useStore();
  const musicStore = useMusicStore();
  const weaveStore = useWeaveStore();
  const { useWebAudio, midiOutputPort, bpm, bpmInterval, isOn, noteHoldCount } = storeToRefs(store);
  const { upperRegisterMax, chordOptions, noteScale, chordSizeFilter, rangeMin, rangeMax, sequenceType, sequenceTypeOptions, sineHarmonics, stackType, stackTypeOptions, rootNote, tonicOptions } = storeToRefs(musicStore);
  const { swatchWidth, swatchDepth, patternOptions, patternType, weaveX, weaveY, euclideanCount } = storeToRefs(weaveStore);
  let activeAccordion = ref('');

  function handleAccordionChange(val) {
    const { origin, pathname} = window.document.location;
    const baseURL = `${origin}${pathname}`;

    history.pushState(null, null, val || baseURL);
  }

  function setAccordion() {
    const { hash } = window.document.location;

    activeAccordion.value = hash;
  }

  function pingGA() {
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-120208217-1');
  }

  function setupHotKeys() {
    // configure command+up/down to control chord selecttion
    hotkeys('command+*', event => {
      const { code } = event;

      if (code === 'ArrowDown') {
        // move down a chordOption
        const currentOptionIndex = _.findIndex(chordOptions.value, item => item.toLowerCase() === noteScale.value.toLowerCase());

        noteScale.value = chordOptions.value[(currentOptionIndex + 1) % chordOptions.value.length];
        event.preventDefault(); // Prevent the default refresh event under WINDOWS system
      } else if (code === 'ArrowUp') {
        // move up a chordOption
        const currentOptionIndex = _.findIndex(chordOptions.value, item => item.toLowerCase() === noteScale.value.toLowerCase());

        noteScale.value = chordOptions.value[(currentOptionIndex - 1 + chordOptions.value.length) % chordOptions.value.length];
        event.preventDefault(); // Prevent the default refresh event under WINDOWS system
      }
    
    });

    // allow computer keyboard to play notes like in Ableton
    // https://sonicbloom.net/ableton-live-tutorial-computer-keyboard-as-midi-controller/
    hotkeys('*', event => {
      switch (event.code.replace('Key', '')) {
        case 'A':
          rootNote.value = 'C';
          break;
        case 'W':
          rootNote.value = 'C#';
          break;  
        case 'S':
          rootNote.value = 'D';
          break;
        case 'E':
          rootNote.value = 'D#';
        case 'D':
          rootNote.value = 'E';
          break;
        case 'F':
          rootNote.value = 'F';
          break;
        case 'T':
          rootNote.value = 'F#';
          break;
        case 'G':
          rootNote.value = 'G';
          break;
        case 'Y':
          rootNote.value = 'G#';
          break;
        case 'H':
          rootNote.value = 'A';
          break;
        case 'U':
          rootNote.value = 'A#';
        case 'J':
          rootNote.value = 'B';
          break;
        case 'K':
          rootNote.value = 'C';
        default:
          break;
      }
    });
  }

  onMounted(() => {
    setAccordion();
    store.initializeWebAudioSynth();
    setupHotKeys();
    pingGA();
  });

  watch(rootNote, store.initNotes);
  watch(sequenceType, store.initNotes);
  watch(sineHarmonics, store.initNotes);
  watch(midiOutputPort, (val) => {
    midi.setOutput(val);
  });
  watch(useWebAudio, val => {
    if (!val) store.getMidiOutputs();
  });

  // clock
  let timer = null;

  function handleTimer() {
    // todo: https://incolumitas.com/2021/12/18/on-high-precision-javascript-timers/
    clearInterval(timer);
    if (isOn.value) {
      timer = setInterval(tick, bpmInterval.value);
    }
  }

  function tick() {
    $event('tick', 'clock.id');
  }

  watch(isOn, val => {
    // to do: determine if this is neccessary
    store.startSynth(); 

    handleTimer();
    if (val) {
      // this.timer = setInterval(this.tick, this.intervalString);
    } else {
      clearInterval(timer);
      // eventBus.emit('clock-off');
      $event('clock-off');
    }
  });
  watch(bpm, () => {
    handleTimer();
  });
</script>

<style lang="scss">
  *,
  *::before,
  *::after {
      box-sizing: border-box;
  }

  html {
      font-size: 100%;
  }

  * {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }

  section {
    margin-bottom: 40px;
  }
  
  #wrapper {
    font-family: sans-serif;
    letter-spacing: .3px;
    background:
      radial-gradient(
        ellipse at top center,
        rgba(250, 250, 250, 1) 40%,
        rgba(229, 229, 229, .9) 100%
      );
    height: 100vh;
    overflow-y: scroll;

  }

  main {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    margin: 10px;
  }

  .app-description {
    margin-bottom: 0;
    width: 100%;
    flex-basis: 100;

    .el-collapse-item__header {
      font-size: 20px;
    }

    .el-collapse-item__content {
      border: dotted black 2px;
      font-size: 14px;
      line-height: 16px;
      margin: auto auto 20px;
      padding: 20px;
      max-width: 728px;
    }

    .el-collapse {
      background-color: none;
      border: none;
      border-bottom: solid black 2px;
      font-size: 12px;
      margin: 0 10px;
    }

    .el-collapse-item__header, .el-collapse-item__wrap {
      background: none;
      border: none;
    }

    a {
      text-decoration: underline;
      color: black;
    }

    p {
      font-size: 14px;
      margin-bottom: 10px;
    }

    figure {
      border: dotted black 2px;
      display: flex;
      flex-direction: row;
      flex-wrap: wrap;
      margin: 15px auto;
      padding: 10px;
      width: 100%;
      justify-content: space-between;
      
      img {
        flex-basis: 100%;
        max-width: 400px;
        margin: auto;
        width: 100%;
      }

      .flex-half {
        width: 40%;
        flex-basis: 48%;
        margin: 0;
      }

      figcaption {
        margin-top: 5px;
        flex-basis: 100%;
        font-size: 10px;
        text-align: center;
      }
    }
  }

  .presets header {
    margin: 20px auto 10px;
    font-size: 16px;
    text-decoration: underline;
  }

  .spotify-embed {
    margin: 20px auto;
    max-width: 600px;
  }

  .config-section, .settings-pane {
    border: solid black 2px;
    flex-basis: 250px;
    flex-grow: 1;
    padding: 10px;
    margin: 10px;

    header {
      font-size: 20px;
      margin-bottom: 10px;
    }

    .settings-description {
      margin-bottom: 10px;
      text-align: justify;
    }

    .setting-title {
      display: inline-block;
    }

    .setting-description {
      font-size: .8em;
    }

    .el-button {
      background-color: transparent;
      border: none;
      padding: 5px;
    }

    .border {
      border: solid black 2px;
      margin-top: 10px;
    }

    .el-slider {
      padding: 0 10px;
    }

    .el-input-number, .el-select {
      display: block;
    }

    .el-popper {
      word-break: normal;
    }
  }
</style>
